/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.io.IOException;
import java.net.InetSocketAddress;

import com.sun.net.httpserver.HttpServer;

public class App {
    public static void main(String[] args) throws IOException {
        int port = 5678;
        HttpServer server = HttpServer.create(new InetSocketAddress(port), 0);
        server.createContext("/", new MyHandler1());
        server.createContext("/sum", new MyHandler2());
        server.setExecutor(null);
        server.start();
    }

    public String getGreeting() {
        return "not Null";
    }
}
